#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e; . src/bash/preludes/gitlab-ci.bash

apt-get -qy update

apt-get -qy install \
  autoconf \
  automake \
  default-jdk \
  default-jre \
  g++ \
  gcc \
  git \
  gnupg \
  gnupg1 \
  jq \
  libtool \
  m4 \
  make \
  maven \
  openssl \
  sshpass \
  texinfo \
  wget \
;

cd safrn0/

./autogen

./configure

make dist
