#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#

set -e; . src/bash/preludes/gitlab-ci.bash

cd "$tmpdir"
tar xzf "$rundir"/*.tar.gz
cd *
install/$1
