#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README.md file.
#

set -e; . src/bash/preludes/gitlab-ci.bash

if ! command -v sudo >/dev/null; then
  su -c "apt-get -qy update && apt-get -qy install sudo" root
fi

sudo apt-get -qy update

sudo apt-get -qy install \
  autoconf \
  automake \
  gcc \
  git \
  jq \
  libtool \
  m4 \
  make \
  texinfo \
  texlive \
;

./autogen

./configure

mkdir public
rmdir public
mv doc/pages public

make doc/safrn.html
mv doc/safrn.html public

make doc/safrn.pdf
mv doc/safrn.pdf public

make doc/safrn.txt
mv doc/safrn.txt public/safrn-utf8.txt

make MAKEINFOFLAGS='-D insertascii' doc/safrn.txt
mv doc/safrn.txt public/safrn-ascii.txt
