#! /bin/bash -
#
# This file is from the SAFRN package.
#
# The following copyright notice is generally applicable:
#
#      Copyright (C)
#         Stealth Software Technologies Commercial, Inc.
#
# The full copyright information depends on the distribution
# of the package. For more information, see the COPYING file.
# However, depending on the context in which you are viewing
# this file, the COPYING file may not be available.
#

set -e; . src/bash/preludes/gitlab-ci.bash

apt-get -qy update

apt-get -qy install \
  autoconf \
  automake \
  build-essential \
  gcc \
  git \
  gnupg \
  gnupg1 \
  jq \
  libgmp-dev \
  libssl-dev \
  libtool \
  m4 \
  make \
  nettle-dev \
  openssl \
  sshpass \
  wget \
;

./autogen

./configure \
;

make docker/safrn-VERSION-docker.tar.xz

PACKAGE_VERSION_DOCKER=$(
  config_h_get_string \
    config.h \
    PACKAGE_VERSION_DOCKER \
  ;
)
readonly PACKAGE_VERSION_DOCKER

case $archivist in
  true)

    r=registry.stealthsoftwareinc.com
    r=$r/stealthcommercial/safrn

    docker push $r:$PACKAGE_VERSION_DOCKER
    docker push $r:latest

  ;;
esac
