#! /bin/bash -
#
# This file is from the SAFRN package.
#
# The following copyright notice is generally applicable:
#
#      Copyright (C)
#         Stealth Software Technologies Commercial, Inc.
#
# The full copyright information depends on the distribution
# of the package. For more information, see the COPYING file.
# However, depending on the context in which you are viewing
# this file, the COPYING file may not be available.
#

set -e; . src/bash/preludes/gitlab-ci.bash

#
#

apt-get -qy update

apt-get -qy install \
  autoconf \
  automake \
  build-essential \
  default-jdk \
  default-jre \
  gcc \
  git \
  gnupg \
  gnupg1 \
  jq \
  libgmp-dev \
  libssl-dev \
  libtool \
  m4 \
  make \
  nettle-dev \
  openssl \
  sshpass \
  texinfo \
  texlive \
  wget \
;

#
#

./autogen

./configure \
;

#
# Install SST.
#

make build-aux/gitbundles/sst.gitbundle
git clone build-aux/gitbundles/sst.gitbundle sst
cd sst
install/on-ubuntu
cd ..

#
# Install Java libraries.
#

make install-java-jardeps

#
#

DCF=
make \
  DISTCHECK_CONFIGURE_FLAGS="$DCF" \
  V=1 \
  VERBOSE=1 \
  distcheck \
;

case $archivist in
  true)

    sh - build-aux/save-artifacts.sh \
      --copy-ssh-secret-key-file \
      --git-committer-email archivist@stealthsoftwareinc.com \
      --git-committer-name "Stealth Archivist" \
      --gpg-passphrase-file /archivist.gpg-passphrase \
      --gpg-secret-key-file /archivist.gpg-secret-key \
      --repository git@gitlab.stealthsoftwareinc.com:stealth/safrn-artifacts.git \
      --ssh-passphrase-file /archivist.ssh-passphrase \
      --ssh-secret-key-file /archivist.ssh-secret-key \
      safrn-*.tar.* \
    ;

  ;;
esac
