#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#

# Load the prelude.
set -e || exit $?
. src/bash/preludes/standard.bash

sst_ubuntu_install_raw lsb-core

v=$(lsb_release -r | sed 's/^[^0-9]*//')
case $v in
  18.0[4-9]* | 18.[1-9]* | 19.* | 20.0[0-3]*)
    v=18.04
  ;;
  20.0[4-9]* | 20.[1-9]* | 21.* | 22.0[0-3]*)
    v=20.04
  ;;
  *)
    sst_barf 'Unsupported Ubuntu version: %s' "$v"
  ;;
esac
readonly v

on_x=on-ubuntu-$v
export on_x

s=src/install/$from_w/$on_x
readonly s

if [[ ! -f "$s" && ! -h "$s" ]]; then
  sst_barf 'Unsupported Ubuntu version: %s' "$v"
fi

"$s" "$@"
