#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

set -e -u -o pipefail

if ! command -v nc >/dev/null 2>&1; then
  echo nc: command not found >&2
  exit 1
fi

expect_all_or_none() {
  local missing=() name present
  for name; do
    eval present=\${$name:+x}
    if [[ ! "$present" ]]; then
      missing+=($name)
    fi
  done
  if [[ ${#missing[@]} != 0 && ${#missing[@]} != $# ]]; then
    IFS=,
    printf 'Either all or none of %s must be given (missing: %s)\n' "$*" "${missing[*]}" >&2
    exit 1
  fi
}; readonly -f expect_all_or_none

expect_all_or_none \
  SAFRN_SSL_CERTIFICATE \
  SAFRN_SSL_CERTIFICATE_KEY \
;

expect_all_or_none \
  SAFRN_SMTP_HOST \
  SAFRN_SMTP_USERNAME \
  SAFRN_SMTP_PASSWORD \
  SAFRN_SMTP_FROM \
;
: ${SAFRN_SMTP_HOST:=}
: ${SAFRN_SMTP_PORT:=25}
: ${SAFRN_SMTP_SSL:=false}
: ${SAFRN_SMTP_STARTTLS:=false}
: ${SAFRN_SMTP_AUTH:=false}
: ${SAFRN_SMTP_USERNAME:=}
: ${SAFRN_SMTP_PASSWORD:=}
: ${SAFRN_SMTP_FROM:=}
readonly SAFRN_SMTP_HOST
readonly SAFRN_SMTP_PORT
readonly SAFRN_SMTP_SSL
readonly SAFRN_SMTP_STARTTLS
readonly SAFRN_SMTP_AUTH
readonly SAFRN_SMTP_USERNAME
readonly SAFRN_SMTP_PASSWORD
readonly SAFRN_SMTP_FROM

if [[ "${SAFRN_SSL_CERTIFICATE-}" ]]; then
  printf 'Setting up NGINX for HTTPS...\n'
  sed "
    s|@SAFRN_SSL_CERTIFICATE@|$SAFRN_SSL_CERTIFICATE|g
    s|@SAFRN_SSL_CERTIFICATE_KEY@|$SAFRN_SSL_CERTIFICATE_KEY|g
  " https.conf >/etc/nginx/conf.d/default.conf
else
  printf 'Setting up NGINX for HTTP...\n'
  cp http.conf /etc/nginx/conf.d/default.conf
fi
printf 'Starting NGINX...\n'
nginx

docker-entrypoint.sh postgres &

while ! nc -z localhost 5432 >/dev/null 2>&1; do
  echo Waiting for postgres to be up...
  sleep 1
done

#
# Spring might not accept command-line options like --foo= to set foo to
# be empty. A workaround is to omit the = and just write --foo. See
# <https://github.com/spring-projects/spring-framework/issues/24464>.
#

java -jar dashboard.jar \
  --spring.mail.host"${SAFRN_SMTP_HOST:+=$SAFRN_SMTP_HOST}" \
  --spring.mail.port"${SAFRN_SMTP_PORT:+=$SAFRN_SMTP_PORT}" \
  --spring.mail.properties.mail.smtp.ssl.enable"${SAFRN_SMTP_SSL:+=$SAFRN_SMTP_SSL}" \
  --spring.mail.properties.mail.smtp.starttls.enable"${SAFRN_SMTP_STARTTLS:+=$SAFRN_SMTP_STARTTLS}" \
  --spring.mail.properties.mail.smtp.auth"${SAFRN_SMTP_AUTH:+=$SAFRN_SMTP_AUTH}" \
  --spring.mail.username"${SAFRN_SMTP_USERNAME:+=$SAFRN_SMTP_USERNAME}" \
  --spring.mail.password"${SAFRN_SMTP_PASSWORD:+=$SAFRN_SMTP_PASSWORD}" \
  --spring.mail.from"${SAFRN_SMTP_FROM:+=$SAFRN_SMTP_FROM}" \
  "$@" \
;
