#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

.SUFFIXES:

.PHONY: all
all:

.PHONY: preview
preview: all push_preview
	@./push_preview $(wiki_url)
