#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README file.
#

. ../../src/bash/preludes/standard.bash || exit

if [[ $# == 1 ]]; then
  wiki_url=$1
else
  printf 'Enter the wiki URL to push the preview to.
For example: git@gitlab.stealthsoftwareinc.com:NAME/safrn.wiki.git
You can skip this prompt with: make wiki_url=URL preview
Wiki URL: ' >&2
  read wiki_url
fi
readonly wiki_url

if [[ "$wiki_url" =~ stealth/safrn ]]; then
  printf 'Refusing to push to the stealth/safrn wiki\n' >&2
  exit 1
fi

cd "$tmpdir"
git clone "$wiki_url" wiki
cd wiki
if git rev-parse HEAD &>/dev/null; then
  git rm "*"
fi
cp -R "$rundir"/* .
git add .
git commit -m "Update the .wiki repository"
git push origin master:master
