#! /bin/bash -
#
# For the copyright information for this file, please search up the
# directory tree for the first README.md file.
#

set -e; . src/bash/preludes/standard.bash

if ! command -v sudo >/dev/null; then
  echo "Installing sudo with yum..."
  su -c "yum -y install sudo" root
fi

echo "Installing various packages with yum..."
sudo sh -c '
  yum install -y epel-release
  yum install -y \
    autoconf \
    automake \
    java-1.8.0-openjdk-headless \
    java-1.8.0-openjdk-devel \
    gcc \
    libtool \
    m4 \
    make \
    openssl \
    sshpass \
    texinfo \
    wget \
    maven \
  ;

  echo "Installing git build-dependencies with yum..."
  yum install -y \
    openssl-devel \
    curl-devel \
    gettext-devel \
  ;
'

safrn_urls=
case ${CI_REPOSITORY_URL+is_set} in
  ?*)
    safrn_urls='safrn_urls="\$(abs_srcdir) $CI_REPOSITORY_URL"'
  ;;
esac
readonly safrn_urls

eval ./configure \
  "$safrn_urls" \
;

install_local_git build-aux/downloads/git-2.20.1.tar.gz

make build-aux/gitbundles/sst.gitbundle
git clone build-aux/gitbundles/sst.gitbundle sst
cd sst
install/on-centos --with-build-groups=default,+java-maven
cd ..

make install-java-jardeps-targets
echo "Installing Java libraries..."
sudo make install-java-jardeps

make_j

make maven-prep
mvn install

echo "Installing..."
sudo sh -c '
  make install
'

if command -v docker >/dev/null; then
  make docker/safrn-docker.tar
fi
