#
# Copyright 2020 Stealth Software Technologies, Inc.
#

FROM ubuntu:18.04

RUN apt-get -q -y update
RUN apt-get -q -y install \
      autoconf \
      automake \
      build-essential \
      wget \
      texinfo \
      gcc \
      g++ \
      jq \
      m4 \
      cmake \
      openssl \
      libssl-dev \
      libtool \
      nlohmann-json-dev \
      libevent-* \
      nettle-dev \
      nettle-bin \
      libgsl23 \
      libgsl-dev
