INSERT INTO roles VALUES (1, 'ADMIN') ON CONFLICT   DO NOTHING;
INSERT INTO roles VALUES (2, 'USER') ON CONFLICT   DO NOTHING;

-- INSERT INTO users VALUES(0,'stealth','$2a$11$i.t/KFIevdihILJeDCoCnOhxpEEesDtdgGi2AxHe3riiWiXseujZy') ON CONFLICT   DO NOTHING;
-- INSERT INTO user_role VALUES(0,1)  ON CONFLICT   DO NOTHING;