#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#

#
# autogen_ac_start [<file>]
#
# Start constructing an accumulative Autoconf source file in which to
# collect autogen output. <file> should specify a file that lives either
# in or below the current directory. If <file> is not given, it defaults
# to autogen.ac.
#

if [[ "$(type -t autogen_ac_start)" == function ]]; then
  return
fi

sst_import_function \
;

autogen_ac_start() {

  case ${autogen_ac_start_has_been_called+x} in
    ?*)
      sst_barf 'autogen_ac_start has already been called'
    ;;
  esac
  autogen_ac_start_has_been_called=x
  readonly autogen_ac_start_has_been_called

  case ${autogen_ac_file+x} in
    ?*)
      sst_barf 'autogen_ac_file is already set'
    ;;
  esac

  case $# in
    0)
      autogen_ac_file=autogen.ac
    ;;
    1)
      autogen_ac_file=$1
    ;;
    *)
      sst_barf 'invalid argument count: %d' $#
    ;;
  esac
  autogen_ac_file=$(sst_dot_slash "$autogen_ac_file" | sst_csf)
  sst_csf autogen_ac_file
  readonly autogen_ac_file

  cat >$autogen_ac_file <<EOF
dnl
dnl For the copyright information for this file, please search up the
dnl directory tree for the first COPYING file.
dnl

dnl
dnl This file was generated by ./autogen.
dnl

[

EOF

  sst_trap_append '
    case $trap_entry_status in
      0)
        case ${autogen_ac_finish_has_been_called+x} in
          "")
            sst_barf "you forgot to call autogen_ac_finish"
          ;;
        esac
      ;;
    esac
  ' EXIT

}

readonly -f autogen_ac_start
